//************************************************************************************
//**  
//**  Source name:   C:\Users\Adão Caxinda Kianga\Documents\curso Microgenio\semaforo.fcfx
//**  Title:         Sémaforo
//**  Description:   New <Arduino Uno R3 PDIP> Embedded Project
//**  Device:        ARD.ATMEGA.ATMEGA328P
//**  
//**  Generated by:  Flowcode v11.0.2.17
//**  Date:          Tuesday, June 16, 2026 17:15:33
//**  Users:         1
//**  Registered to: FernandesCaxinda (FREE_VERSION)
//**  Licence key: TCW03R
//**  
//**  
//**     NOT FOR COMMERCIAL USE
//**  
//**  https://www.flowcode.co.uk
//**  
//************************************************************************************


#define MX_ARD

#define MX_CAL_ARD

#define MX_CLK_SPEED 16000000

#define FCP_NULL Unconnected_Port

#define MX_UART_ID
#define MX_UART_UCSRC

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <avr\io.h>
#include <avr\interrupt.h>
#include <avr\eeprom.h>
#include <avr\wdt.h>

//ICD functionality
#define USE_FLOWCODE_ICD3
#define ICD_CLK_PORT 3
#define ICD_DATA_PORT 3
#define ICD_CLK_PIN 1
#define ICD_DATA_PIN 0
#define ICD_NUM_BPS 8
signed int brk_pnt[ICD_NUM_BPS] = {-1, -1, -1, -1, -1, -1, -1, -1};
#define ICD_STACK_SIZE 8
unsigned char icd_stack[ICD_STACK_SIZE] = {0, 0, 0, 0, 0, 0, 0, 0};
#define ICD_ID0 0x1f
#define ICD_ID1 0x4f
#define ICD_ID2 0xff
#define ICD_ID3 0xef
#define ICD_ID4 0xfd
#define ICD_ID5 0x95
#define ICD_ID6 0x6c
#define ICD_ID7 0x90

//ICD3 info
#define ICD3_TYPE com
#define ICD3_CHANNEL 1
#define ICD3_BAUD 115200
#define ICD3_RX_PORT 3
#define ICD3_RX_PIN 0
#define ICD3_TX_PORT 3
#define ICD3_TX_PIN 1



/*========================================================================*\
   Use :Include the type definitions
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\internals.c"




void FCM_QUANDO_O_BOTAO_FOR_PRECIONADO();
void FCM_NewMacro();
MX_UINT8 FCD_05261_switch_base__ReadState();
void FCD_05261_switch_base__WaitUntilHigh();
void FCD_05261_switch_base__WaitUntilLow();
void FCD_03d93_led_base__TurnOn();
void FCD_03d93_led_base__TurnOff();
void FCD_03d92_led_base__TurnOn();
void FCD_03d92_led_base__TurnOff();
void FCD_03d91_led_base__TurnOn();
void FCD_03d91_led_base__TurnOff();

/*========================================================================*\
   Use :Include the chip adaption layer
\*========================================================================*/
#include "C:\ProgramData\MatrixTSL\FlowcodeV11\CAL\includes.c"


/*========================================================================*\
   Use :switch_base
       :GUID: 953a042a-b2aa-4f2e-94e2-ee2979cfc92e
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\switch.fcpx
       :Version: 4.0 (0x100128)
       :Timestamp: 02\02\2023
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Reads the button state as 0 for released or 1 for pressed
       :Performs debounce if required
       :
       :Returns : MX_UINT8
\*=----------------------------------------------------------------------=*/
MX_UINT8 FCD_05261_switch_base__ReadState()
{
  //Local variable definitions
  MX_UINT16 FCL_DEL_COUNT;
  MX_UINT8 FCL_OLD_SWITCHVAL;
  MX_UINT8 FCR_RETVAL;


  #if (1)
    if (1 != GET_PORT_PIN(C, 1))
    {    

      FCR_RETVAL = 1;

    } else {

      FCR_RETVAL = 0;

    }

    #if (1) // 10 > 0
      FCL_DEL_COUNT = 0;
      FCL_OLD_SWITCHVAL = FCR_RETVAL;

      while (1)
      {
        if ((FCL_DEL_COUNT < 10) == 0) break;
        FCI_DELAYBYTE_MS(1);

        if (1 != GET_PORT_PIN(C, 1))
        {        

          FCR_RETVAL = 1;

        } else {

          FCR_RETVAL = 0;

        }

        if (FCR_RETVAL == FCL_OLD_SWITCHVAL)
        {        

          FCL_DEL_COUNT = FCL_DEL_COUNT + 1;

        } else {

          FCL_DEL_COUNT = 0;

        }

        FCL_OLD_SWITCHVAL = FCR_RETVAL;

      }

    // #else
    //Code has been optimised out by the pre-processor
    #endif

  #else
  //Code has been optimised out by the pre-processor
  #endif

  return (FCR_RETVAL);

}

/*=----------------------------------------------------------------------=*\
   Use :Waits until the switch is in state 'high'
       :The interpretation of 'high' depends on the polarity
\*=----------------------------------------------------------------------=*/
void FCD_05261_switch_base__WaitUntilHigh()
{
  //Local variable definitions
  MX_UINT8 FCL_SWITCHVAL = (0xff); // The state of the pin
  MX_UINT16 FCL_DEL_COUNT;
  MX_UINT8 FCL_OLD_SWITCHVAL;


  #if (1)
    while (1)
    {
      FCL_SWITCHVAL = GET_PORT_PIN(C, 1);

      #if (1) // 1 == 1
        FCL_SWITCHVAL = !FCL_SWITCHVAL;

      // #else
      //Code has been optimised out by the pre-processor
      #endif

      #if (1) // 10 > 0
        FCL_DEL_COUNT = 0;
        FCL_OLD_SWITCHVAL = FCL_SWITCHVAL;

        while (1)
        {
          if ((FCL_DEL_COUNT < 10) == 0) break;
          FCI_DELAYBYTE_MS(1);

          FCL_SWITCHVAL = GET_PORT_PIN(C, 1);

          #if (1) // 1 == 1
            FCL_SWITCHVAL = !FCL_SWITCHVAL;

          // #else
          //Code has been optimised out by the pre-processor
          #endif

          if (FCL_SWITCHVAL == FCL_OLD_SWITCHVAL)
          {          

            FCL_DEL_COUNT = FCL_DEL_COUNT + 1;

          } else {

            FCL_DEL_COUNT = 0;

          }

          FCL_OLD_SWITCHVAL = FCL_SWITCHVAL;

        }

      // #else
      //Code has been optimised out by the pre-processor
      #endif

      if ((FCL_SWITCHVAL == 1) == 0) break;
    }

  // #else
  //Code has been optimised out by the pre-processor
  #endif

}

/*=----------------------------------------------------------------------=*\
   Use :Waits until the switch is in state 'low'
       :The interpretation of 'high' depends on the polarity
\*=----------------------------------------------------------------------=*/
void FCD_05261_switch_base__WaitUntilLow()
{
  //Local variable definitions
  MX_UINT8 FCL_SWITCHVAL; // The state of the pin
  MX_UINT16 FCL_DEL_COUNT;
  MX_UINT8 FCL_OLD_SWITCHVAL;


  #if (1)
    while (1)
    {
      FCL_SWITCHVAL = GET_PORT_PIN(C, 1);

      #if (1) // 1 == 1
        FCL_SWITCHVAL = !FCL_SWITCHVAL;

      // #else
      //Code has been optimised out by the pre-processor
      #endif

      #if (1) // 10 > 0
        FCL_DEL_COUNT = 0;
        FCL_OLD_SWITCHVAL = FCL_SWITCHVAL;

        while (1)
        {
          if ((FCL_DEL_COUNT < 10) == 0) break;
          FCI_DELAYBYTE_MS(1);

          FCL_SWITCHVAL = GET_PORT_PIN(C, 1);

          #if (1) // 1 == 1
            FCL_SWITCHVAL = !FCL_SWITCHVAL;

          // #else
          //Code has been optimised out by the pre-processor
          #endif

          if (FCL_SWITCHVAL == FCL_OLD_SWITCHVAL)
          {          

            FCL_DEL_COUNT = FCL_DEL_COUNT + 1;

          } else {

            FCL_DEL_COUNT = 0;

          }

          FCL_OLD_SWITCHVAL = FCL_SWITCHVAL;

        }

      // #else
      //Code has been optimised out by the pre-processor
      #endif

      if ((FCL_SWITCHVAL != 1) == 0) break;
    }

  // #else
  //Code has been optimised out by the pre-processor
  #endif

}

#define FCA_SW_ROCKER_NEON1 0xb831
#define FCV_SW_ROCKER_NEON1 0x03b1

/*========================================================================*\
   Use :led_base
       :GUID: a7b05886-784c-48c8-a6f6-cc371c7728e1
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\led_base.fcpx
       :Version: 7.0 (0x10031e)
       :Timestamp: 19\09\2023
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Turn the LED on.
       :Active high - The pin is configured to output high.
       :Active low - The pin is configured to output low.
\*=----------------------------------------------------------------------=*/
void FCD_03d93_led_base__TurnOn()
{

#if 0 // Disabled code
  // ::Debug.PrintLn("Enabled = " + String Enabled)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

  #if (1)
#if 0 // Disabled code
    // ::Debug.PrintLn("True branch")

#endif // Disabled code

    SET_PORT_PIN(B, 3, 0);

  #else
  //Code has been optimised out by the pre-processor
  #endif

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("polarity = " + String polarity)

#endif // Disabled code

}

/*=----------------------------------------------------------------------=*\
   Use :Turn the LED off.
       :Active high - The pin is configured to output low.
       :Active low - The pin is configured to output high.
\*=----------------------------------------------------------------------=*/
void FCD_03d93_led_base__TurnOff()
{

  #if (1)
    SET_PORT_PIN(B, 3, 1 - 0);

  // #else
  //Code has been optimised out by the pre-processor
  #endif

}

#define FCA_LED_5MM_CLIP3 0xe743
#define FCV_LED_5MM_CLIP3 0x01bd

/*========================================================================*\
   Use :led_base
       :GUID: a7b05886-784c-48c8-a6f6-cc371c7728e1
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\led_base.fcpx
       :Version: 7.0 (0x10031e)
       :Timestamp: 19\09\2023
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Turn the LED on.
       :Active high - The pin is configured to output high.
       :Active low - The pin is configured to output low.
\*=----------------------------------------------------------------------=*/
void FCD_03d92_led_base__TurnOn()
{

#if 0 // Disabled code
  // ::Debug.PrintLn("Enabled = " + String Enabled)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

  #if (1)
#if 0 // Disabled code
    // ::Debug.PrintLn("True branch")

#endif // Disabled code

    SET_PORT_PIN(B, 4, 0);

  #else
  //Code has been optimised out by the pre-processor
  #endif

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("polarity = " + String polarity)

#endif // Disabled code

}

/*=----------------------------------------------------------------------=*\
   Use :Turn the LED off.
       :Active high - The pin is configured to output low.
       :Active low - The pin is configured to output high.
\*=----------------------------------------------------------------------=*/
void FCD_03d92_led_base__TurnOff()
{

  #if (1)
    SET_PORT_PIN(B, 4, 1 - 0);

  // #else
  //Code has been optimised out by the pre-processor
  #endif

}

#define FCA_LED_5MM_CLIP2 0xe742
#define FCV_LED_5MM_CLIP2 0x0165

/*========================================================================*\
   Use :led_base
       :GUID: a7b05886-784c-48c8-a6f6-cc371c7728e1
       :Location: C:\ProgramData\MatrixTSL\FlowcodeV11\Components\led_base.fcpx
       :Version: 7.0 (0x10031e)
       :Timestamp: 19\09\2023
       :Variable declarations
       :Macro implementations
\*========================================================================*/
/*=----------------------------------------------------------------------=*\
   Use :Turn the LED on.
       :Active high - The pin is configured to output high.
       :Active low - The pin is configured to output low.
\*=----------------------------------------------------------------------=*/
void FCD_03d91_led_base__TurnOn()
{

#if 0 // Disabled code
  // ::Debug.PrintLn("Enabled = " + String Enabled)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

  #if (1)
#if 0 // Disabled code
    // ::Debug.PrintLn("True branch")

#endif // Disabled code

    SET_PORT_PIN(B, 5, 0);

  #else
  //Code has been optimised out by the pre-processor
  #endif

#if 0 // Disabled code
  // ::Debug.PrintLn("pin = " + String pin)

#endif // Disabled code

#if 0 // Disabled code
  // ::Debug.PrintLn("polarity = " + String polarity)

#endif // Disabled code

}

/*=----------------------------------------------------------------------=*\
   Use :Turn the LED off.
       :Active high - The pin is configured to output low.
       :Active low - The pin is configured to output high.
\*=----------------------------------------------------------------------=*/
void FCD_03d91_led_base__TurnOff()
{

  #if (1)
    SET_PORT_PIN(B, 5, 1 - 0);

  // #else
  //Code has been optimised out by the pre-processor
  #endif

}

#define FCA_LED_5MM_CLIP1 0xe741
#define FCV_LED_5MM_CLIP1 0x0035
#define FCA_LEDMONO3 0xe9e3
#define FCV_LEDMONO3 0x002b
#define FCA_LEDMONO2 0xe9e2
#define FCV_LEDMONO2 0x0021
#define FCA_LEDMONO1 0xe9e1
#define FCV_LEDMONO1 0x000d

/*========================================================================*\
   Use :User Project
       :Variable declarations
       :Macro implementations
\*========================================================================*/
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_GLOBAL MX_BOOL FCV_BOTAOPEDESTRE = (1);

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_QUANDO_O_BOTAO_FOR_PRECIONADO()
{

ICD_PUSH(1);


  FC_MARKER(1);

  FC_MARKER(2);

  // Delay
  FCI_DELAYBYTE_S(2);

  FC_MARKER(3);

  // GREEN
  SET_PORT_PIN(B,5,(1));

  FC_MARKER(4);

  // YELLOW
  SET_PORT_PIN(B,4,(0));

  FC_MARKER(5);

  // Delay
  FCI_DELAYBYTE_S(1);

  FC_MARKER(6);

  // YELLOW
  SET_PORT_PIN(B,4,(1));

  FC_MARKER(7);

  // RED
  SET_PORT_PIN(B,3,(0));

  FC_MARKER(8);

  // Delay
  FCI_DELAYBYTE_S(3);

  FC_MARKER(9);

  // RED
  SET_PORT_PIN(B,3,(1));

  FC_MARKER(10);

ICD_POP();


}

/*=----------------------------------------------------------------------=*\
   Use :
\*=----------------------------------------------------------------------=*/
void FCM_NewMacro()
{

ICD_PUSH(2);


  FC_MARKER(11);

  FC_MARKER(12);

  // GREEN
  SET_PORT_PIN(B,5,(1));

  FC_MARKER(13);

  // YELLOW
  SET_PORT_PIN(B,4,(1));

  FC_MARKER(14);

  // RED
  SET_PORT_PIN(B,3,(1));

  FC_MARKER(15);

ICD_POP();


}



/*========================================================================*\
   Use :Main
\*========================================================================*/
int main()
{
	MCUSR=0x00;


	//Enable initial stop condition
	dbg_mode = 0x08;

	ICD_PUSH(0);


  FC_MARKER(16);

  FC_MARKER(17);

  // INICIAR EM NIVEL 1
  FCM_NewMacro();

  FC_MARKER(25);

  // Loop
  while (1)
  {
    FC_MARKER(25);

    if ((1) == 0) break;
    FC_MARKER(19);

    // GREEN
    SET_PORT_PIN(B,5,(0));

    FC_MARKER(20);

    // Input
    FCV_BOTAOPEDESTRE = GET_PORT_PIN(C,1);

    FC_MARKER(21);

    // Decision
    if (FCV_BOTAOPEDESTRE == 0)
    {    

      FC_MARKER(22);

      // PRECIIONADO
      FCM_QUANDO_O_BOTAO_FOR_PRECIONADO();

      FC_MARKER(24);

    // } else {

      FC_MARKER(23);

      FC_MARKER(23);

      FC_MARKER(24);

    }

    FC_MARKER(18);

  }

  FC_MARKER(26);

	ICD_POP();

	//Code to signal end of program to ICD
	dbg_mode = 0x08;

	FC_MARKER(-1);


	mainendloop: goto mainendloop;
}



/*========================================================================*\
   Use :Interrupt
\*========================================================================*/
#ifdef USE_FLOWCODE_ICD3
ICD_INTERRUPT_HANDLER
#endif




